### ISSUE TITLE
Better way in python

### ISSUE THREAD

**Issue by adalseno** [RMHogervorst/bigger_then_memory#1]
Great job, it was nice to read.
In python instead of:
```
# this is not ideal, there must be a nicer way than this.
sales["pos_sales"] = 0
sales["pos_sales"][sales["sales_units"] > 0] = sales["sales_units"][sales["sales_units"] > 0]
```
it would be better to do (the `pandas` way):
```
sales['pos_sales'] = sales['sales_units'].where(sales['sales_units'] > 0, 0)
```

it's (much) faster and does not give you any warning about modifying a slice of a DataFrame, that is not granted to work; otherwise you should use `loc` to be sure, like this:
```
sales["pos_sales"] = 0
sales.loc[sales["sales_units"] > 0, "pos_sales"] = sales["sales_units"][sales["sales_units"] > 0]
```

For very (very) large datasets using `np.where` might be slightly faster (for 1E6 rows there isn't any significant difference):
```
sales['pos_sales'] = np.where(sales['sales_units']> 0, sales['sales_units'], 0)
```

**Comment by RMHogervorst** [comment]
excellent! thank you, I often do this wrong!

**Comment by adalseno** [comment]
Pandas sometimes is weird.
You may also pack everything in a single function like this:
```
(sales.assign(
        pos_sales= lambda x: x['sales_units'].where(x['sales_units'] > 0, 0),
        euros = lambda x : x["sales_units"] * x["item_price_eur"],
        euros_sku = lambda x : x["pos_sales"] * x["item_price_eur"] )
        .groupby(["month", "year", "SKU"], as_index=False)
        .agg({
            "item_price_eur":["mean"],
            "euros":["sum"],
            "euros_sku":["max", "count"]
            })
        .set_axis(["month", "year", "SKU","avg_price_SKU","total_revenue","max_price_SKU", "items_sold" ], axis=1))
```
to have a flatten index (using as_index=False in the group by we don't need to reset the index; we need one more column, euros_sku, in pandas to perform the calculation using pos_sales that in your code has not been used, but the result does not seem to change; I have added count to get the same results as the n() function in R) or use 
```
(sales.assign(
    pos_sales= lambda x: x['sales_units'].where(x['sales_units'] > 0, 0),
    euros = lambda x : x["sales_units"] * x["item_price_eur"],
    euros_sku = lambda x : x["pos_sales"] * x["item_price_eur"] )
    .groupby(["month", "year", "SKU"], as_index=False)
    .agg({
        "item_price_eur":[("avg_price_SKU","mean")],
        "euros":[("total_revenue","sum")],
        "euros_sku":[("max_price_SKU","max"), ("items_sold","count")]
     }))
```
to keep the multi-index header, renaming the aggregate columns .
There is a library called siuba https://github.com/machow/siuba that aims to "port" dyplr syntax to pandas (honestly I never used it, but you may want to give it a try).

**Comment by RMHogervorst** [comment]
I'll try to add this to the post too. Thanks!
