### ISSUE TITLE
Great Post + quick Question for duck SQL query example code

### ISSUE THREAD

**Issue by sfd99** [RMHogervorst/bigger_then_memory#2]
**_Hi Roel,_**

Thanks for your great blog post!

**Q:**
Could you please include 
the example code
for using a SQL query
 with the **"duck"**  sales.db  ?.

You already show a SQL query
 for the **SQLite** sales db:

```
# write sql yourself :
head(DBI::dbGetQuery(con,  "SELECT SKU, year, sales_units * item_price_eur AS total_revenue FROM sales GROUP BY year, SKU"))
```

The above SQL query code for SQLite works!.

But, I can't get  
the equivalent **duck.db** SQL query example to work...

For **duck**, I tried:
```
head(DBI::dbGetQuery(duck,  "SELECT SKU, year, sales_units * item_price_eur AS total_revenue FROM sales GROUP BY year, SKU"))
```

Help!.
Learning from your examples,
_Thanks, Roel!_

**SFd99
San Francisco
Rstudio
Ubuntu Linux 20.04**

**Comment by RMHogervorst** [comment]
Hi @sfd99, thanks for your question! I just tried and you are absolutely right, I think I forgat a sum somewhere.
You might wonder how I debugged this?
I hacked it, by doing this:

```r
sales_dtbl %>% 
      group_by(month, year, SKU) %>% 
      mutate(pos_sales = case_when(
        sales_units > 0 ~ sales_units,
        TRUE ~ 0
      )) %>% 
      summarise(
        total_revenue = sum(sales_units * item_price_eur),
        max_order_price = max(pos_sales * item_price_eur),
        avg_price_SKU = mean(item_price_eur),
        items_sold = n()
      ) %>% show_query()
```
I ran the query and added a `show_query()` command.

that returned this query which had the sum command in the top 

```r
SQL>
SELECT "month", "year", "SKU", SUM("sales_units" * "item_price_eur") AS "total_revenue", MAX("pos_sales" * "item_price_eur") AS "max_order_price", AVG("item_price_eur") AS "avg_price_SKU", COUNT(*) AS "items_sold"
FROM (SELECT "month", "year", "sales_units", "SKU", "item_price_eur", CASE
WHEN ("sales_units" > 0.0) THEN ("sales_units")
ELSE (0.0)
END AS "pos_sales"
FROM "sales") "q01"
GROUP BY "month", "year", "SKU"
```

I've updated this repo with your tip!
